project:
  type: website
  output-dir: docs
  resources: 
    - library/**
    - trainings/**

website:
  navbar:
    search: true
    pinned: true
    left:
      - index.qmd
  
  sidebar:
    logo: images/logo.png
    style: docked
    collapse-level: 1
    contents:
      - section: "Getting Started"
        contents:
          - training.qmd
      - section: "Operations"
        contents:
          - shieldedOps.qmd
          - insurance.qmd
      - updates.qmd
  
  page-footer:
    left: "© 2026 University of California"
    center: "Public Safety UAS Portal"
    right:
      - text: "Contact"
        href: mailto:uassafety@ucmerced.edu
      - text: "GitHub"
        href: https://github.com/ucdrones/public-safety/



format:
  html:
    theme: default # bootstrap 5 default
    fontsize: 1.1em
    linestretch: 1.7
    toc: true



