---
title: "UC Drones Public Safety Portal"
format: html
---

# Welcome {-}

The **UC Center of Excellence on Unmanned Aircraft System Safety** has developed this portal of resources for all **Public Safety** users of Unmanned Aircraft Systems within the University of California.

## UC Drone Web App {-}
For submitting UC flight requests and reports, please visit http://ehs.ucop.edu/drones




::: {.callout-warning}
**DJI, Autel, and other drones manufactured in China are banned from use on federally funded projects.**

**The FCC has also prohibited authorization of new foreign‑manufactured drones.**

Review your fleet and projects immediately. Contact the UAS COE with any questions.
:::



## Connect with Us {-}
Send us an email at UASsafety@ucmerced.edu if you'd like to join our UC Drone [email listserv](mailto:uassafety@ucmerced.edu?subject=UC%20Drone%20Listserv%20Request&body=Please%20sign%20me%20up%20for%20the%20UC%20Drone%20listserv) 

Want to schedule an online appointment to chat?  Use our [Booking link](https://outlook.office365.com/owa/calendar/UCCenterofExcellenceonUASSafety@merced.onmicrosoft.com/bookings/)

- Find a time that works for you and the system will schedule a MS Teams meeting for us.

## Quick Links {-}


**[Unmanned Aircraft System (Drone) Policy](https://policy.ucop.edu/doc/3500671/Drone)** - The UC Presidential Policy on the use of Unmanned Aircraft Systems within the University of California.

**[Drone Map of California](https://ucdrones.github.io/map)** -  Map of UC properties, County/City regulations, and public lands.

**[NASA ASRS](https://asrs.arc.nasa.gov/uassafety.html)** - NASA UAS Safety Reporting